name: Sync to Gitee

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  sync:
    name: Mirror to Gitee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        run: |
          git remote add gitee "https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/jkin8010/mopng-desktop.git"
          git push gitee --all
          git push gitee --tags
